# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'My Passwords' do

pod 'AFNetworking', '0.9.1'

end

target 'My PasswordsTests' do

end

target 'My PasswordsUITests' do

end
